function main
clear 
close all
clc
global  hax start_tag fail_tag
fail_tag = 0;
screen_size = get(0,'screensize');
mean_size = mean(screen_size(3:4));
hf = figure('resize','off','name','',...
    'position', [mean_size*0.25 mean_size*0.1 mean_size*0.7467 mean_size*0.56], 'numbertitle', 'off');
hax = axes;
set(gcf,'menubar', 'none','color', [0.3 0.3 0.3])
set(gca,'position',[0.2300    0.1100    0.7750    0.8150])
set(gca, 'xlim', [0, 6], 'ylim', [0, 6])
set(hax, 'xtick', [], 'ytick', [], 'box', 'on')
set(hax, 'color', [0.7 0.6 0.6])
set(hax, 'DataAspectRatio', [1 1 1], 'PlotBoxAspectRatio', [1 1 1])
x = repmat([1; 5], 1, 5);
y = [1:5; 1:5];
line(x, y, 'color', 'k', 'linewidth', 3)
line(y, x, 'color', 'k', 'linewidth', 3)

start_tag = 1;
uicontrol('style', 'text', 'string', '2048 game', 'fontsize', 40, 'fontname', 'Times New Roman',...
    'units', 'normal', 'position', [0.02,0.75,0.26,0.14], 'parent', hf, ...
    'ForegroundColor', 'w', 'backgroundcolor', [0.3 0.3 0.3],...
    'fontweight', 'bold');
uicontrol('style', 'pushbutton', 'string', 'Start', 'fontsize', 18, 'fontname', 'Times New Roman',...
    'units', 'normal', 'position', [0.04 0.6 0.1 0.1], 'parent', hf, ...
    'fontweight', 'bold', 'callback', @start);
uicontrol('style', 'pushbutton', 'string', 'Restart', 'fontsize',18, 'fontname', 'Times New Roman',...
    'units', 'normal', 'position',[0.18 0.6 0.1, 0.1], 'parent', hf,...
    'fontweight', 'bold', 'callback', @restart);

% operation uicontrol

uicontrol('style', 'pushbutton', 'string', 'left', 'fontsize',18, 'fontname', 'Times New Roman',...
    'units', 'normal', 'position',[0.02 0.3 0.1, 0.1], 'parent', hf,...
    'fontweight', 'bold', 'callback', @left_operation);
uicontrol('style', 'pushbutton', 'string', 'right', 'fontsize',18, 'fontname', 'Times New Roman',...
    'units', 'normal', 'position',[0.2 0.3 0.1, 0.1], 'parent', hf,...
    'fontweight', 'bold', 'callback', @right_operation);
uicontrol('style', 'pushbutton', 'string', 'up', 'fontsize',18, 'fontname', 'Times New Roman',...
    'units', 'normal', 'position',[0.1 0.45 0.1, 0.1], 'parent', hf,...
    'fontweight', 'bold', 'callback', @up_operation);
uicontrol('style', 'pushbutton', 'string', 'down', 'fontsize',18, 'fontname', 'Times New Roman',...
    'units', 'normal', 'position',[0.1 0.15 0.1, 0.1], 'parent', hf,...
    'fontweight', 'bold', 'callback', @down_operation);
end